language: java
sudo: false # faster builds
cache:
  directories:
    - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_script:
  - python html2text.py target/site/surefire-report.html
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6d8ab6e1fea3df1be908
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always